# fly.toml file generated for stanfordgoose on 2022-08-30T01:54:46-07:00

app = "stanfordgoose"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  SWAP = "1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 7500
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
